### ISSUE TITLE
[QUESTION] How can I use authentication for npm registry but skip authentication when accessing github?

### ISSUE THREAD

**Issue by miguelsosa** [npm/npm-registry-fetch#12]
# What / Why

I use artifactory as my proxy for npmjs.  To use artifactory I need to do authenticated access for both reading and writing.  I am using:

```
2 info using npm@6.10.3
3 info using node@v12.4.0
```

My .npmrc looks similar to:

```
always-auth=true
_auth=REDACTED
registry=https://...
```

This works fine for accessing packages from registry.npmjs.org

However, one of my dependencies depends on a package form github directly:

    "node-csv": "https://github.com/voodootikigod/node-csv/tarball/master"

When npm gets to this file it tries to pass authentication information and fails:

```
23 http fetch GET 401 https://github.com/voodootikigod/node-csv/tarball/master 629ms
24 silly fetchPackageMetaData error for node-csv@https://github.com/voodootikigod/node-csv/tarball/master Unable to authenticate, need: Basic realm="GitHub"
25 timing stage:rollbackFailedOptional Completed in 0ms
26 timing stage:runTopLevelLifecycles Completed in 11321ms
27 silly saveTree nodetest@1.0.0
27 silly saveTree └── debug@4.1.1
28 verbose stack Error: Unable to authenticate, need: Basic realm="GitHub"
28 verbose stack     at /Users/msosa/.homebrew/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:94:17
28 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:89:5)
29 verbose statusCode 401
30 verbose pkgid node-csv@https://github.com/voodootikigod/node-csv/tarball/master
```

I have tried adding to my .npmrc lines like:
```
//github.com/:always-auth=false
//github.com/:_auth=''
```
and similar but it always seems to pass (incorrect) auth information.

How can I tell npm-registry-fetch to skip authentication for github.com but use it for everything else?

**Comment by miguelsosa** [comment]
I was able to get past this issue by removing all entries with always-auth=true

it seems like even if I set always-auth=false at the 'root' level of the .npmrc, and always-auth=true at the registry level //registry/:always-auth= true, having a single always-auth causes it to try to do authentication to github. I am not clear why - perhaps the way npm uses this it just saves the last always-auth it reads as an option and really uses it always. I  don' tknow if ther eis a way to say auth always for a particular registry.

**Comment by mk-pmb** [comment]
Any news or official solution for this?

**Comment by isaacs** [comment]
npm v7 scopes all authorization to a registry now.  The next release will do so much more consistently.  This is not something we can fix in v6, unfortunately.  Even if v6 was not in "maintenance but only for severe bugs" mode, it'd be a breaking change.
