### ISSUE TITLE
[BUG] 30s default timeout is too small

### ISSUE THREAD

**Issue by isaacs** [npm/npm-registry-fetch#26]
# What / Why

See https://github.com/npm/cli/issues/1151

The documented default timeout of 30s was not being set in v4, so we "fixed the glitch" in nrf 4.0.3, causing problems for people.

There's no npm v6 way to specify what timeout to use, so not having a timeout at all seems like a reasonable default for the v4 line, at least.  Let's roll back that change, and document it.  (Arguably, fixing this bug was a breaking change, and we ought to roll it back.)

For latest/npm v7, it seems like 30s is way too small.  We should add a `--fetch-timeout` config on the cli, which defaults to 3000 (5m) or so, and also use that as the default here.

**Comment by ruyadorno** [comment]
sounds good to me :+1:

**Comment by isaacs** [comment]
Fixed by #27
