### ISSUE TITLE
[BUG] Link to wiki page for "No auth for URI, but auth present for scoped registry" is broken

### ISSUE THREAD

**Issue by grimsa** [npm/npm-registry-fetch#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `npm ci` in some case the following can get printed:
```
npm warn registry No auth for URI, but auth present for scoped registry.
npm warn registry
npm warn registry URI: https://npm.pkg.github.com/download/@my-org/my-artifact/0.24.0/fb5ceb32ac7240d811746913fbe277d47b******
npm warn registry Scoped Registry Key: //my-org.com/my-npm-registry/
npm warn registry
npm warn registry More info here: https://github.com/npm/cli/wiki/No-auth-for-URI,-but-auth-present-for-scoped-registry
```

The problem is that the link that is printed is broken: https://github.com/npm/cli/wiki/No-auth-for-URI,-but-auth-present-for-scoped-registry (tested in latest Chrome and Firefox).

### Expected Behavior

Instead the link should be: https://github.com/npm/cli/wiki/%22No-auth-for-URI,-but-auth-present-for-scoped-registry%22

As far as I can see, the link is hardcoded here: https://github.com/npm/npm-registry-fetch/blob/0a9f05be03a8410edffbbf3dc121a930c21535ac/lib/check-response.js#L10

The [wiki page itself](https://github.com/npm/cli/wiki/%22No-auth-for-URI,-but-auth-present-for-scoped-registry%22#background) should show output with correct link.

**Comment by wraithgar** [comment]
It's easier to fix the wiki page to not quote the title.  Fixed.
