### ISSUE TITLE
Missing v4.0.5 Git tag in repo

### ISSUE THREAD

**Issue by davidlj95** [npm/npm-registry-fetch#32]
So that we can know how the logging sensitive info vulnerability was fixed

**Comment by jportela** [comment]
Here's the relevant commit: https://github.com/npm/npm-registry-fetch/commit/18bf9b97fb1deecdba01ffb05580370846255c88#diff-b49b5d13952110b509e66f7261ef1c70

But I agree having the label would help finding it faster

**Comment by davidlj95** [comment]
Thanks! 

Yup, as a repo maintainer I use to check the [CHANGELOG](https://github.com/npm/npm-registry-fetch/blob/v4/CHANGELOG.md) to review changes and as the tag is missing, I had to go to the commit manually (not a big issue though :P)

But I also use to have a link to that in the comment updating the dependency in the repo, and couldn't do that as didn't find the tag 
https://github.com/npm/npm-registry-fetch/blob/v4.0.5/CHANGELOG.md

**Comment by claudiahdz** [comment]
Tags have been fixed!
