### ISSUE TITLE
[BUG] remove the isFromCI option and npm-in-ci header

### ISSUE THREAD

**Issue by isaacs** [npm/npm-registry-fetch#39]
We never set this in npm v7.  It's literally doing nothing.  Just remove it.

**Comment by venkatramanareddy** [comment]
@isaacs I've removed references of these options from code, can you take a look?

**Comment by darcyclarke** [comment]
Landed in: https://github.com/npm/npm-registry-fetch/pull/44 thanks to: https://github.com/npm/npm-registry-fetch/pull/43
