### ISSUE TITLE
Does this work in the browser?

### ISSUE THREAD

**Issue by felixfbecker** [npm/npm-registry-fetch#4]
Since this is based on `fetch` and doesn't seem to read npm settings from disk, can this package be made to work in the browser? I.e. it could use `isomorphic-fetch`, or a different entry point for the browser that does not import node-things.

**Comment by evocateur** [comment]
I highly doubt it, considering it does stuff with `streams` and `zlib` and whatnot. The `fetch` implementation is [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen), which explicitly wraps `node-fetch`, not a browser-compatible module.

**Comment by isaacs** [comment]
Not likely to ever make this work in a web browser.  It depends on make-fetch-happen, which wraps cacache and minipass-fetch, both of which are highly node-specific.

It would potentially be possible to create a `make-fetch-happen` fork that used the browser fetch and caching, but that would be the place to shim, not here.
