### ISSUE TITLE
Breaking changes in v9.0.0?

### ISSUE THREAD

**Issue by fishcharlie** [npm/npm-registry-fetch#40]
@nlf Looks like you deployed v9.0.0 (d77b165284d51243c54d70be326c077f439a6195) a few months ago, but no updates were made to the CHANGELOG in regards to what breaking changes this version includes.

When comparing tags, it doesn't even look like this release has any breaking changes (https://github.com/npm/npm-registry-fetch/compare/v8.1.5...latest).

What are the breaking changes in v9.0.0? And if there are none, why does this package not follow [SEMVER](https://semver.org)?

**Comment by nlf** [comment]
The commit immediately before the one you linked, here: https://github.com/npm/npm-registry-fetch/commit/3eb3f6292a3d12d7eec39f79c1e922f54d70463d

Is where the breaking change took place. We removed an option. We are working on our release processes to help us with things like changelogs, but in the mean time the commit history should generally be pretty readable.
